// CardioLab — transparent 0D cardiovascular engine.
// Inspired by the compartmental / variable-elastance framework of Ursino (1998),
// Guyton-style venous return and Windkessel concepts. Educational, not clinical.
const clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
const pos=x=>Math.max(0,x);
const expSafe=x=>Math.exp(clamp(x,-40,40));
export const BASELINE={hr:72,bloodVolume:5,preloadScale:1,contractility:100,afterloadScale:1,sympathetic:20,radius:1,arterialComplianceScale:1,venousComplianceScale:1,pulmonaryResistanceScale:1,respiratoryRate:14,tidalVolume:.5,intrathoracicPressure:-4,coronaryOcclusion:0,territory:'none',scenario:'normal'};
const y0={Psa:92,Psp:54,Pep:50,Psv:5,Pev:5,Ppa:15,Ppp:11,Ppv:7,Vra:45,Vrv:110,Vla:55,Vlv:120};
function activation(t,T){let x=(t/T)%1;if(x<0)x+=1;return{atrial:Math.exp(-Math.pow((x-.12)/.055,2)),vent:Math.exp(-Math.pow((x-.28)/.18,2))};}
function valve(Pin,Pout,R){return pos((Pin-Pout)/R);}
function atrial(V,C,Vu,a,g){return Math.max(-2,(V-Vu)/C+a*g);}
function vent(V,E,V0,P0,k,phi,ext){const pd=P0*Math.max(0,expSafe(k*Math.max(V-V0,0))-1);const ps=Math.max(0,E*(V-V0));return ext+(1-phi)*pd+phi*ps;}
function params(input){const x={...BASELINE,...input};const r=clamp(x.radius,.45,1.8),r4=Math.pow(r,-4),sym=clamp(x.sympathetic/100,0,2),contract=clamp(x.contractility/100,.25,2),is=clamp(x.coronaryOcclusion/100,0,1);const tone=clamp(x.afterloadScale*r4*(1+.22*sym),.25,4.5),pt=clamp(x.pulmonaryResistanceScale,.25,6);return{...x,cycle:60/x.hr,Rsa:.72*tone,Rsp:1.15*tone,Rep:1.35*tone,Rsv:.018,Rev:.018,Rpa:.08*pt,Rpp:.22*pt,Rpv:.018*pt,Csa:1.55*x.arterialComplianceScale,Csp:.95*x.arterialComplianceScale,Cep:1.10*x.arterialComplianceScale,Csv:85*x.venousComplianceScale,Cev:55*x.venousComplianceScale,Cpa:3.8,Cpp:4.2,Cpv:18,EmaxLV:2.95*contract*(1-.45*is),EmaxRV:1.75*contract*(1-.2*is),V0LV:16.77,V0RV:40.8,P0LV:1.5,P0RV:1.5,kLV:.014,kRV:.011,VraU:25,VlaU:25,MV:.0025,TV:.0025,AV:.004,PV:.004};}
function derivative(y,t,p){const a=activation(t,p.cycle),pRA=atrial(y.Vra,31.25*p.venousComplianceScale,p.VraU,a.atrial,2.5),pLA=atrial(y.Vla,19.23*p.venousComplianceScale,p.VlaU,a.atrial,2),pRV=vent(y.Vrv,p.EmaxRV,p.V0RV,p.P0RV,p.kRV,a.vent,p.intrathoracicPressure),pLV=vent(y.Vlv,p.EmaxLV,p.V0LV,p.P0LV,p.kLV,a.vent,p.intrathoracicPressure),qMV=valve(pLA,pLV,p.MV),qTV=valve(pRA,pRV,p.TV),qAV=valve(pLV,y.Psa,p.AV),qPV=valve(pRV,y.Ppa,p.PV),qSaSp=pos((y.Psa-y.Psp)/p.Rsp),qSaEp=pos((y.Psa-y.Pep)/p.Rep),qSpSv=pos((y.Psp-y.Psv)/p.Rsv),qEpEv=pos((y.Pep-y.Pev)/p.Rev),qSvRA=pos((y.Psv-pRA)/p.Rsa),qEvRA=pos((y.Pev-pRA)/p.Rsa),qPaPp=pos((y.Ppa-y.Ppp)/p.Rpp),qPpPv=pos((y.Ppp-y.Ppv)/p.Rpv),qPvLA=pos((y.Ppv-pLA)/p.Rpv);return{d:{Psa:(qAV-qSaSp-qSaEp)/p.Csa,Psp:(qSaSp-qSpSv)/p.Csp,Pep:(qSaEp-qEpEv)/p.Cep,Psv:(qSpSv-qSvRA)/p.Csv,Pev:(qEpEv-qEvRA)/p.Cev,Ppa:(qPV-qPaPp)/p.Cpa,Ppp:(qPaPp-qPpPv)/p.Cpp,Ppv:(qPpPv-qPvLA)/p.Cpv,Vra:qSvRA+qEvRA-qTV,Vrv:qTV-qPV,Vla:qPvLA-qMV,Vlv:qMV-qAV},pressures:{pRA,pLA,pRV,pLV},flows:{qMV,qTV,qAV,qPV}};}
function rk4(y,t,dt,p){const a=derivative(y,t,p).d,y2={};for(const k in y)y2[k]=Math.max(0,y[k]+dt*a[k]/2);const b=derivative(y2,t+dt/2,p).d,y3={};for(const k in y)y3[k]=Math.max(0,y[k]+dt*b[k]/2);const c=derivative(y3,t+dt/2,p).d,y4={};for(const k in y)y4[k]=Math.max(0,y[k]+dt*c[k]);const d=derivative(y4,t+dt,p).d,o={};for(const k in y)o[k]=Math.max(0,y[k]+dt*(a[k]+2*b[k]+2*c[k]+d[k])/6);return o;}
function trace(input){const p=params(input);let y={...y0},t=0;const dt=.005,settle=Math.max(4,Math.min(7,p.cycle*6)),start=settle-p.cycle,n=260,tr=[];for(let i=0;i<Math.ceil(settle/dt);i++){if(t>=start&&tr.length<n){const z=derivative(y,t,p);tr.push({t:t-start,...y,...z.pressures,...z.flows});}y=rk4(y,t,dt,p);t+=dt;}return{p,tr};}
function ecg(p,input){const is=clamp(input.coronaryOcclusion/100,0,1);return Array.from({length:420},(_,i)=>{const x=i/419;let y=.015*Math.sin(2*Math.PI*x)+.20*Math.exp(-Math.pow((x-.16)/.035,2))-Math.exp(-Math.pow((x-.395)/.008,2))+.30*Math.exp(-Math.pow((x-.415)/.013,2))+.27*Math.exp(-Math.pow((x-.68)/.065,2));if(is)y+=(input.territory==='LAD'?.42:input.territory==='RCA'?-.30:.30)*is*Math.exp(-Math.pow((x-.52)/.08,2));return{x:x*p.cycle*1000,y};});}
function phono(p,input){return Array.from({length:420},(_,i)=>{const x=i/419;let y=.85*Math.exp(-Math.pow((x-.055)/.009,2))+.72*Math.exp(-Math.pow((x-.40)/.010,2));if(input.scenario==='aorticStenosis')y+=.48*Math.exp(-Math.pow((x-.22)/.065,2));if(input.scenario==='mitralStenosis')y+=.38*Math.exp(-Math.pow((x-.68)/.05,2));if(input.scenario==='mitralRegurgitation')y+=.35*Math.exp(-Math.pow((x-.22)/.09,2));if(input.scenario==='aorticRegurgitation')y+=.24*Math.exp(-Math.pow((x-.58)/.10,2));return{x:x*p.cycle*1000,y};});}
export function simulate(input){const{p,tr}=trace(input),avg=k=>tr.reduce((s,z)=>s+(z[k]||0),0)/tr.length,mx=k=>Math.max(...tr.map(z=>z[k]||0)),mn=k=>Math.min(...tr.map(z=>z[k]||0));const q=avg('qAV'),co=q*60,sv=q*1000/p.hr,edv=mx('Vlv'),esv=mn('Vlv'),ef=clamp(sv/Math.max(edv,1)*100,1,95),map=avg('Psa'),sbp=mx('Psa'),dbp=mn('Psa'),pap=avg('Ppa'),rap=avg('pRA'),lap=avg('pLA'),pms=clamp(7+3.8*(input.bloodVolume-5)*input.venousComplianceScale+3*(input.preloadScale-1),1,18),effectiveSVR=clamp(80*(map-rap)/Math.max(co,.1),100,6000),effectivePVR=clamp(80*(pap-lap)/Math.max(co,.1),20,1800),do2=co*13.8*.98*10,vo2=250,oxygenExtraction=clamp(vo2/Math.max(do2,1),.12,.98),perf=clamp(co/5*(1400/Math.max(effectiveSVR,250)),.1,2.5),anaerobic=clamp(Math.pow(Math.max(0,(.65-perf)/.5),1.7)+Math.max(0,oxygenExtraction-.35)*.5,0,1.5),lactate=clamp(1+4.4*anaerobic+(input.scenario==='septic'?.6:0),.7,12);return{...input,cycle:p.cycle,co,sv,edv,esv,ef,map,sbp,dbp,pulsePressure:sbp-dbp,pms,rap,lap,pap,effectiveSVR,effectivePVR,do2,vo2,oxygenExtraction,perf,anaerobic,lactate,pulmonaryCongestion:clamp((lap-10)*8+(pap-18)*2,0,100),systemicCongestion:clamp((rap-5)*8,0,100),coronaryPerfusion:clamp(dbp-rap,5,180)*(1-input.coronaryOcclusion/100),lvPressure:tr.map(z=>({x:z.t*1000,y:z.pLV})),rvPressure:tr.map(z=>({x:z.t*1000,y:z.pRV})),aortic:tr.map(z=>({x:z.t*1000,y:z.Psa})),pulmonary:tr.map(z=>({x:z.t*1000,y:z.Ppa})),atrial:tr.map(z=>({x:z.t*1000,y:z.pLA})),lvVolume:tr.map(z=>({x:z.t*1000,y:z.Vlv})),aorticFlow:tr.map(z=>({x:z.t*1000,y:z.qAV*1000})),pv:tr.map(z=>({x:z.Vlv,y:z.pLV})),ecg:ecg(p,input),phonocardiogram:phono(p,input),modelParams:p};}
export function guytonCurves(r){const cardiac=[],venous=[];for(let x=-4;x<=12;x+=.1){const f=clamp((x+4)/10,0,1);cardiac.push({x,y:clamp(r.co*(.45+.85*f)*(r.contractility/100),0,14)});venous.push({x,y:x>=r.pms?0:clamp((r.pms-x)/Math.max(1,.8*r.venousComplianceScale),0,14)});}return{cardiac,venous,intersection:{x:r.rap,y:r.co}};}
export function frankStarling(r){return Array.from({length:70},(_,i)=>{const x=40+i*2;return{x,y:18+105*(1-Math.exp(-x/80))*(.72+.28*r.contractility/100)}});}
export const arterialWave=r=>r.aortic;
export const pulsePressureSeries=r=>r.aortic.map(z=>({x:z.x,y:Math.max(0,z.y-r.dbp)}));
export const causalChain=(a,b)=>{if(b.radius<a.radius)return['Raio ↓','R ∝ 1/r⁴','Resistência ↑↑','Fluxo regional ↓','DO₂ ↓','Lactato tende ↑'];if(b.radius>a.radius)return['Raio ↑','Resistência ↓','Fluxo regional ↑','Perfusão ↑'];if(b.bloodVolume<a.bloodVolume)return['Volume ↓','Pms ↓','Retorno venoso ↓','Pré-carga ↓','VS/DC ↓'];if(b.contractility<a.contractility)return['Contratilidade ↓','Emax ↓','ESV ↑','VS ↓','DC ↓'];if(b.pvr>a.pvr)return['RVP ↑','Pós-carga VD ↑','PAP ↑','Fluxo pulmonar comprometido'];if(b.afterload>a.afterload)return['Pós-carga ↑','Pressão contra ejeção ↑','VS pode ↓'];if(b.hr>a.hr)return['FC ↑','Ciclo encurta','Diástole encurta proporcionalmente mais','Enchimento pode ↓'];return['Variável alterada','Circuito acoplado resolvido','Pressões/fluxos atualizados','Gráficos sincronizados'];};
