import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, HeartPulse, Gauge, Droplets, RotateCcw, Play, Pause, Crosshair, ChevronDown, BarChart3, BookOpen, Layers3, ExternalLink } from 'lucide-react';
import Model3D from './Model3D.jsx';
import PhysiologyCharts from './PhysiologyCharts.jsx';
import { BASELINE, simulate, ecgCycle } from './physiology.js';
import { REFERENCES } from './references.js';
import './styles.css';

function Slider({label,value,min,max,step=1,unit,onChange,hint}){return <div className="slider-row"><div className="slider-top"><span>{label}</span><b>{value}{unit}</b></div><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/>{hint&&<small>{hint}</small>}</div>}
function ECG({hr,playing}){const points=useMemo(()=>ecgCycle(hr),[hr]);return <div className="ecg-card"><div className="ecg-header"><span><Activity size={14}/> ECG • Lead II</span><span className="live"><i/> {playing?'LIVE':'PAUSED'}</span></div><svg viewBox="0 0 720 100" preserveAspectRatio="none" className="ecg-svg"><defs><pattern id="ecgGrid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0L0 0 0 20" fill="none" stroke="rgba(255,255,255,.08)" strokeWidth="1"/></pattern></defs><rect width="720" height="100" fill="url(#ecgGrid)"/><polyline points={points} fill="none" stroke="#64e4b7" strokeWidth="2.2"/></svg><div className="ecg-stats"><span>HR <b>{hr}</b> bpm</span><span>RR <b>{(60000/hr).toFixed(0)}</b> ms</span><span>PR <b>160</b> ms</span><span>QRS <b>88</b> ms</span></div></div>}
function References(){return <div className="references"><div className="reference-hero"><span className="eyebrow">SOURCE CONTROL</span><h2>Model provenance & references</h2><p>Equations are implemented as transparent educational models. Textbook figures are reconstructed from mathematical relationships rather than copied. 3D anatomy is sourced from open/reference datasets where licensing permits.</p></div><div className="reference-grid">{REFERENCES.map((r,i)=><article className="reference-card" key={i}><div className="reference-tag">{r.category}</div><h3>{r.title}</h3><span>{r.year}</span><p>{r.note}</p><a href={r.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={12}/></a></article>)}</div></div>}
function App(){
 const [v,setV]=useState(BASELINE);const [playing,setPlaying]=useState(true);const [tab,setTab]=useState('monitor');const [view,setView]=useState('model');
 const p=simulate(v);const set=k=>val=>setV(old=>({...old,[k]:val}));const reset=()=>setV({...BASELINE});
 return <main className="app"><header className="topbar"><div className="brand"><div className="brand-mark"><HeartPulse size={20}/></div><div><strong>Cardio<span>Lab</span></strong><small>PHYSIOLOGY • HEMODYNAMICS • 3D</small></div></div><div className="status"><span className="status-dot"/> MODEL ONLINE <span className="divider"/> EDUCATIONAL MODE</div><button className="reset" onClick={reset}><RotateCcw size={14}/> Reset</button></header>
 <section className="workspace">
  <aside className="left-panel panel"><div className="panel-title"><div><span className="eyebrow">PHYSIOLOGICAL CONTROLS</span><h2>Hemodynamics</h2></div><ChevronDown size={16}/></div>
   <div className="section-label">CARDIAC</div><Slider label="Heart rate" value={v.hr} min={30} max={180} unit=" bpm" onChange={set('hr')} hint="Chronotropy"/><Slider label="End-diastolic volume" value={v.edv} min={50} max={220} unit=" mL" onChange={set('edv')} hint="Preload / filling"/><Slider label="End-systolic volume" value={v.esv} min={20} max={130} unit=" mL" onChange={set('esv')}/><Slider label="Contractility" value={v.contractility} min={40} max={180} unit=" %" onChange={set('contractility')} hint="Inotropy / ESPVR"/>
   <div className="section-label">VASCULAR</div><Slider label="Preload" value={v.preload} min={40} max={180} unit=" %" onChange={set('preload')}/><Slider label="Afterload" value={v.afterload} min={40} max={220} unit=" %" onChange={set('afterload')}/><Slider label="Systemic vascular resistance" value={v.svr} min={400} max={3000} step={10} unit=" dyn·s/cm⁵" onChange={set('svr')}/><Slider label="Pulmonary vascular resistance" value={v.pvr} min={50} max={900} step={5} unit=" dyn·s/cm⁵" onChange={set('pvr')}/>
   <div className="section-label">COMPLIANCE & VOLUME</div><Slider label="Blood volume" value={v.bloodVolume} min={2.5} max={8} step={0.1} unit=" L" onChange={set('bloodVolume')}/><Slider label="Central venous pressure" value={v.cvp} min={0} max={20} step={0.5} unit=" mmHg" onChange={set('cvp')}/><Slider label="Arterial compliance" value={v.arterialCompliance} min={0.5} max={3} step={0.1} unit=" ×" onChange={set('arterialCompliance')} hint="Windkessel parameter"/><Slider label="Venous compliance" value={v.venousCompliance} min={50} max={180} step={5} unit=" ×" onChange={set('venousCompliance')} hint="Controls Pms"/><Slider label="Sympathetic tone" value={v.sympathetic} min={0} max={100} unit=" %" onChange={set('sympathetic')} hint="Prepared for baroreflex layer"/>
  </aside>
  <section className="center-panel"><div className="view-header"><div><span className="eyebrow">CARDIOVASCULAR SIMULATION ENVIRONMENT</span><h1>{view==='model'?'Reference cardiovascular anatomy':view==='curves'?'Mathematical physiology':'Model provenance'}</h1></div><div className="view-actions"><button className="view-tab" onClick={()=>setView('model')}><Layers3 size={14}/> 3D</button><button className="view-tab" onClick={()=>setView('curves')}><BarChart3 size={14}/> CURVES</button><button className="view-tab" onClick={()=>setView('refs')}><BookOpen size={14}/> SOURCES</button><button className="icon-btn"><Crosshair size={15}/></button><button className="play-btn" onClick={()=>setPlaying(x=>!x)}>{playing?<Pause size={14}/>:<Play size={14}/>} {playing?'PAUSE':'RUN'}</button></div></div>
   {view==='model'&&<><div className="model-wrap"><div className="model-grid"/><Model3D hr={v.hr} playing={playing} params={p}/><div className="flow-legend"><span className="arterial-dot"/> arterial <span className="venous-dot"/> venous <span className="anatomy-key"/> reference anatomy</div></div><div className="model-bottom"><div><span>HEART RATE</span><b>{v.hr} <em>BPM</em></b></div><div><span>CARDIAC OUTPUT</span><b>{p.co.toFixed(1)} <em>L/MIN</em></b></div><div><span>MEAN ARTERIAL PRESSURE</span><b>{p.map.toFixed(0)} <em>MMHG</em></b></div><div><span>MEAN SYSTEMIC FILLING PRESSURE</span><b>{p.pms.toFixed(1)} <em>MMHG</em></b></div></div></>}
   {view==='curves'&&<div className="curves-wrap"><PhysiologyCharts p={p}/><div className="model-note"><b>Model note</b> Curves are generated from the simulator's equations at the current parameter state. They are intended to make the relationships in Guyton, ventricular pressure-volume analysis and Windkessel models explorable—not to substitute for validated clinical simulation software.</div></div>}
   {view==='refs'&&<References/>}
  </section>
  <aside className="right-panel panel"><div className="tabs"><button className={tab==='monitor'?'active':''} onClick={()=>setTab('monitor')}>MONITOR</button><button className={tab==='ecg'?'active':''} onClick={()=>setTab('ecg')}>ECG</button></div>{tab==='monitor'?<><div className="section-label">REAL-TIME PARAMETERS</div><div className="vitals-grid"><div className="vital"><HeartPulse/><small>HEART RATE</small><strong>{v.hr}</strong><span>bpm</span></div><div className="vital"><Gauge/><small>MAP</small><strong>{p.map.toFixed(0)}</strong><span>mmHg</span></div><div className="vital"><Activity/><small>CARDIAC OUTPUT</small><strong>{p.co.toFixed(1)}</strong><span>L/min</span></div><div className="vital"><Droplets/><small>VENOUS RETURN</small><strong>{p.venousReturn.toFixed(1)}</strong><span>L/min</span></div></div><div className="section-label">HEMODYNAMIC MONITOR</div><div className="metric"><span>SBP / DBP</span><b>{p.sbp.toFixed(0)} / {p.dbp.toFixed(0)} <i>mmHg</i></b></div><div className="metric"><span>STROKE VOLUME</span><b>{p.sv.toFixed(0)} <i>mL</i></b></div><div className="metric"><span>EJECTION FRACTION</span><b>{p.ef.toFixed(0)} <i>%</i></b></div><div className="metric"><span>LV SYSTOLIC PRESSURE</span><b>{p.lvSys.toFixed(0)} <i>mmHg</i></b></div><div className="metric"><span>RV SYSTOLIC PRESSURE</span><b>{p.rvSys.toFixed(0)} <i>mmHg</i></b></div><div className="metric"><span>PULMONARY ARTERY MEAN</span><b>{p.papMean.toFixed(0)} <i>mmHg</i></b></div><div className="metric"><span>CORONARY PERFUSION GRADIENT</span><b>{p.coronaryPerfusion.toFixed(0)} <i>mmHg</i></b></div><div className="metric"><span>VENOUS GRADIENT</span><b>{p.venousGradient.toFixed(1)} <i>mmHg</i></b></div><ECG hr={v.hr} playing={playing}/></>:<><div className="section-label">ELECTROPHYSIOLOGY</div><ECG hr={v.hr} playing={playing}/><div className="ecg-explain"><b>Sinus rhythm model</b><span>Waveform morphology is synthetic and linked to the current cycle length. It is not a diagnostic ECG generator.</span></div><div className="metric"><span>R–R INTERVAL</span><b>{p.rr.toFixed(0)} <i>ms</i></b></div><div className="metric"><span>PR INTERVAL</span><b>160 <i>ms</i></b></div><div className="metric"><span>QRS DURATION</span><b>88 <i>ms</i></b></div><div className="metric"><span>QTc</span><b>410 <i>ms</i></b></div></>}</aside>
 </section><footer><span>CardioLab v0.4 • clinical flow map • reference anatomy</span><span>Educational simulator • not for clinical decision-making</span></footer></main>
}
createRoot(document.getElementById('root')).render(<App/>);
