export const VARIABLE_INFO={
 hr:{label:'Frequência cardíaca',short:'FC',unit:'bpm',definition:'Número de ciclos cardíacos por minuto.',formula:'FC = 60 / intervalo RR',up:['Exercício','febre','catecolaminas','hipovolemia compensada','hipertireoidismo'],down:['Sono','condicionamento físico','hipotermia','bloqueadores beta','disfunção do nó sinusal'],pathologies:['Taquiarritmias','Bradicardia','Choque hipovolêmico','Sepse'],range:[30,180],step:1},
 map:{label:'Pressão arterial média',short:'PAM',unit:'mmHg',definition:'Pressão média efetiva de perfusão da circulação sistêmica durante o ciclo.',formula:'PAM ≈ PAD + 1/3(PAS − PAD)',up:['Aumento de RVS','Aumento de volume circulante','Aumento do débito cardíaco'],down:['Vasodilatação','Hemorragia','Diminuição do débito cardíaco'],pathologies:['Hipertensão arterial','Choque','Sepse','Hemorragia','Estenose aórtica','Insuficiência cardíaca']},
 co:{label:'Débito cardíaco',short:'DC',unit:'L/min',definition:'Volume de sangue bombeado por cada ventrículo por minuto.',formula:'DC = FC × VS',up:['Exercício','Aumento do retorno venoso','Catecolaminas'],down:['Insuficiência cardíaca','Hipovolemia','Infarto extenso','Arritmias'],pathologies:['Choque cardiogênico','Insuficiência cardíaca','Sepse','Hemorragia']},
 sv:{label:'Volume sistólico',short:'VS',unit:'mL',definition:'Volume ejetado pelo ventrículo durante uma sístole.',formula:'VS = VDF − VSF',up:['Pré-carga','Contratilidade','Redução moderada da pós-carga'],down:['Hipovolemia','Baixa contratilidade','Aumento importante da pós-carga'],pathologies:['Insuficiência cardíaca','Estenose aórtica','IAM']},
 preload:{label:'Pré-carga',short:'Pré-carga',unit:'%',definition:'Estiramento/filling ventricular no final da diástole; em modelos simples relaciona-se ao volume diastólico final.',formula:'Aproximação: pré-carga ∝ VDF',up:['Volume sanguíneo','Retorno venoso','Venoconstrição'],down:['Hemorragia','Desidratação','Venodilatação'],pathologies:['Choque hipovolêmico','Insuficiência cardíaca']},
 afterload:{label:'Pós-carga',short:'Pós-carga',unit:'%',definition:'Carga contra a qual o ventrículo deve ejetar sangue.',formula:'Para o VE, relacionada à pressão/estresse de parede durante a ejeção.',up:['RVS','Pressão arterial','Estenose aórtica'],down:['Vasodilatação','Hipotensão'],pathologies:['Hipertensão','Estenose aórtica','Choque distributivo']},
 svr:{label:'Resistência vascular sistêmica',short:'RVS',unit:'dyn·s/cm⁵',definition:'Resistência oferecida pela circulação sistêmica ao fluxo.',formula:'RVS ≈ 80 × (PAM − PVC) / DC',up:['Simpático α1','Angiotensina II','Vasoconstrição'],down:['Óxido nítrico','Bradicinina','Histamina','Sepse'],pathologies:['Hipertensão','Sepse','Choque distributivo']},
 pvr:{label:'Resistência vascular pulmonar',short:'RVP',unit:'dyn·s/cm⁵',definition:'Resistência ao fluxo através da circulação pulmonar.',formula:'RVP ≈ 80 × (PAPm − PCP) / DC',up:['Hipóxia alveolar','TEP','Doença vascular pulmonar'],down:['Recrutamento vascular','Oxigênio em hipóxia pulmonar'],pathologies:['Hipertensão pulmonar','TEP','DPOC']},
 cvp:{label:'Pressão venosa central',short:'PVC',unit:'mmHg',definition:'Pressão próxima à pressão do átrio direito e indicador de condições de enchimento direito.',formula:'PVC ≈ pressão atrial direita',up:['Falência direita','Hipervolemia','Tamponamento'],down:['Hipovolemia','Venodilatação'],pathologies:['Insuficiência cardíaca direita','Tamponamento','TEP']},
 arterialCompliance:{label:'Complacência arterial',short:'Complacência',unit:'×',definition:'Mudança de volume por unidade de mudança de pressão.',formula:'C = ΔV / ΔP',up:['Idade jovem','Artérias menos rígidas'],down:['Envelhecimento','Aterosclerose','Hipertensão crônica'],pathologies:['Rigidez arterial','Aterosclerose']},
 radius:{label:'Raio vascular',short:'Raio',unit:'×',definition:'Raio efetivo de um segmento vascular; pequenas mudanças têm grande efeito sobre resistência.',formula:'R ∝ 1/r⁴ (Poiseuille)',up:['Vasodilatação','Óxido nítrico','β₂'],down:['Vasoconstrição','Simpático α1','Endotelina'],pathologies:['Choque distributivo','Hipertensão','Isquemia']},
 bloodVolume:{label:'Volume sanguíneo',short:'Volume',unit:'L',definition:'Volume total de sangue circulante.',formula:'Volume = plasma + elementos figurados',up:['Retenção de Na⁺/água','Transfusão'],down:['Hemorragia','Desidratação','Diurese'],pathologies:['Choque hemorrágico','Insuficiência cardíaca']},
 contractility:{label:'Contratilidade',short:'Contratilidade',unit:'%',definition:'Capacidade intrínseca do miocárdio de gerar força em determinada condição de carga.',formula:'Relacionada à elastância sistólica final (ESPVR)',up:['Simpático β1','Catecolaminas','Digoxina'],down:['Isquemia','Acidose','Hipóxia','β-bloqueio'],pathologies:['IAM','Insuficiência cardíaca sistólica','Choque cardiogênico']},
 respiratoryRate:{label:'Frequência respiratória',short:'FR',unit:'irpm',definition:'Número de ciclos respiratórios por minuto.',formula:'Ventilação-minuto = FR × VT',up:['Febre','Acidose','Ansiedade','Hipoxemia'],down:['Depressão do SNC','Opioides','Fadiga respiratória'],pathologies:['Sepse','Acidose metabólica','Insuficiência respiratória']},
 tidalVolume:{label:'Volume corrente',short:'VT',unit:'L',definition:'Volume de gás mobilizado em cada ciclo respiratório.',formula:'VA = FR × (VT − espaço morto)',up:['Inspiração profunda','Ventilação mecânica'],down:['Restrição','Fadiga'],pathologies:['SDRA','Doença neuromuscular']},
 intrathoracicPressure:{label:'Pressão intratorácica',short:'PIT',unit:'mmHg',definition:'Pressão dentro do tórax que influencia retorno venoso e transmuralidade cardíaca.',formula:'Ptransmural = Pinterna − Pexterna',up:['PEEP','Pneumotórax hipertensivo','Manobra de Valsalva'],down:['Inspiração espontânea'],pathologies:['Pneumotórax hipertensivo','Tamponamento','Ventilação mecânica']},
 lactate:{label:'Lactato',short:'Lactato',unit:'mmol/L',definition:'Marcador metabólico que pode aumentar quando a oferta de oxigênio é insuficiente ou quando há aumento de produção/alterações de depuração.',formula:'DO₂ = DC × conteúdo arterial de O₂',up:['Hipoperfusão','Choque','Crise convulsiva','β-adrenérgico'],down:['Restauração da perfusão','Clearance hepático/renal'],pathologies:['Choque séptico','Choque cardiogênico','Choque hipovolêmico']}
};
export const CONTROL_GROUPS=[
 {title:'Cardíaco',keys:['hr','edv','esv','contractility']},
 {title:'Vascular',keys:['preload','afterload','svr','pvr','radius']},
 {title:'Volume & pressão',keys:['bloodVolume','cvp','arterialCompliance','venousCompliance','intrathoracicPressure']},
 {title:'Respiratório',keys:['respiratoryRate','tidalVolume']}
];
